# Generated by Django 4.2.5 on 2024-04-29 13:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0002_alter_stockbodegaetiquetado_fecha_etiquetado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('cuit_cuil', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('mayorista', 'Mayorista'), ('minorista', 'Minorista'), ('consumidor final', 'Consumidor Final')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCorrienteAcreedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compras', models.ManyToManyField(related_name='cuenta_corriente_acreedores', to='contabilidad.compracuentacorriente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicion', models.CharField(choices=[('Contado', 'Contado'), ('Cuenta corriente', 'Cuenta corriente'), ('Tarjeta de credito', 'Tarjeta de credito'), ('Debito automatico', 'Debito automatico'), ('Donacion', 'Donacion'), ('online', 'online'), ('Transferencia', 'Transferencia')], max_length=50)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cliente')),
                ('deposito', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.deposito')),
            ],
        ),
        migrations.CreateModel(
            name='ProveedorInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('cuit_cuil', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuenta_corriente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_insumos_relacionado', to='contabilidad.cuentacorrienteacreedores')),
            ],
        ),
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_envio', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('medio', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cliente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.venta')),
            ],
        ),
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_deuda', models.DateField(auto_now_add=True)),
                ('fecha_fin_deuda', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVentaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('prod_empaquetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta_empaquetado', to='administracion.moverstockempaquetado')),
                ('prod_etiquetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta_etiquetado', to='administracion.moverstocketiquetado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_sucursal', to='contabilidad.venta')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('prod_empaquetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.stockbodegaempaquetado')),
                ('prod_etiquetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.stockbodegaetiquetado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.venta')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCorrienteDeudores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_corriente_clientes', to='contabilidad.cliente')),
                ('ventas', models.ManyToManyField(related_name='cuenta_corriente_deudores', to='contabilidad.ventacuentacorriente')),
            ],
        ),
        migrations.AddField(
            model_name='cuentacorrienteacreedores',
            name='proveedor_insumos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_corriente_proveedores_insumos', to='contabilidad.proveedorinsumos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuenta_corriente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_relacionado', to='contabilidad.cuentacorrientedeudores'),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('cantidad', models.IntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='contabilidad.carrito')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='Acreedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_acreedor', models.DateField(auto_now_add=True)),
                ('fecha_fin_acreedor', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('proveedor_insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.proveedorinsumos')),
            ],
        ),
    ]
