# Generated by Django 4.2.5 on 2024-02-03 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('cuit_cuil', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('tipo', models.CharField(choices=[('mayorista', 'Mayorista'), ('minorista', 'Minorista'), ('final', 'Consumidor Final')], max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CompraCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CuentaCorrienteAcreedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('compras', models.ManyToManyField(related_name='cuenta_corriente_acreedores', to='contabilidad.compracuentacorriente')),
            ],
        ),
        migrations.CreateModel(
            name='VentaCuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('descripcion', models.TextField()),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confirmada', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProveedorInsumos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=50, null=True)),
                ('cuit_cuil', models.CharField(max_length=50)),
                ('direccion', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('telefono', models.CharField(max_length=50)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('cuenta_corriente', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='proveedor_insumos_relacionado', to='contabilidad.cuentacorrienteacreedores')),
            ],
        ),
        migrations.CreateModel(
            name='Deudor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_deuda', models.DateField(auto_now_add=True)),
                ('fecha_fin_deuda', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCorrienteDeudores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_corriente_clientes', to='contabilidad.cliente')),
                ('ventas', models.ManyToManyField(related_name='cuenta_corriente_deudores', to='contabilidad.ventacuentacorriente')),
            ],
        ),
        migrations.AddField(
            model_name='cuentacorrienteacreedores',
            name='proveedor_insumos',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_corriente_proveedores_insumos', to='contabilidad.proveedorinsumos'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='cuenta_corriente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cliente_relacionado', to='contabilidad.cuentacorrientedeudores'),
        ),
        migrations.CreateModel(
            name='Acreedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio_acreedor', models.DateField(auto_now_add=True)),
                ('fecha_fin_acreedor', models.DateField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('proveedor_insumos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.proveedorinsumos')),
            ],
        ),
    ]
