# Generated by Django 4.2.5 on 2024-02-03 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='tipo',
            field=models.CharField(choices=[('mayorista', 'Mayorista'), ('minorista', 'Minorista'), ('consumidor final', 'Consumidor Final')], max_length=50),
        ),
    ]
