# Generated by Django 4.2.5 on 2024-02-05 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0056_alter_stockbodegaetiquetado_fecha_etiquetado'),
        ('contabilidad', '0002_alter_cliente_tipo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('condicion', models.CharField(choices=[('Contado', 'Contado'), ('Cuenta corriente', 'Cuenta corriente'), ('Tarjeta de credito', 'Tarjeta de credito'), ('Debito automatico', 'Debito automatico'), ('Donacion', 'Donacion'), ('Ventas en linea', 'Ventas en linea'), ('Transferencia', 'Transferencia')], max_length=50)),
                ('fecha_venta', models.DateTimeField(auto_now_add=True)),
                ('comprador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='DetalleVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('prod_empaquetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.stockbodegaempaquetado')),
                ('prod_etiquetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.stockbodegaetiquetado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='contabilidad.venta')),
            ],
        ),
    ]
