# Generated by Django 4.2.5 on 2024-02-05 21:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0057_alter_stockbodegaetiquetado_fecha_etiquetado'),
        ('contabilidad', '0003_venta_detalleventa'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='deposito',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.deposito'),
        ),
    ]
