# Generated by Django 4.2.5 on 2024-02-05 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0059_alter_stockbodegaetiquetado_fecha_etiquetado'),
        ('contabilidad', '0004_venta_deposito'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleVentaSucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('prod_empaquetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta_empaquetado', to='administracion.moverstockempaquetado')),
                ('prod_etiquetado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detalles_venta_etiquetado', to='administracion.moverstocketiquetado')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_sucursal', to='contabilidad.venta')),
            ],
        ),
    ]
