# Generated by Django 4.2.5 on 2024-02-06 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0005_detalleventasucursal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventasucursal',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
    ]
