# Generated by Django 4.2.5 on 2024-02-06 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0006_alter_detalleventasucursal_precio_unitario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalleventa',
            name='precio_unitario',
            field=models.IntegerField(),
        ),
    ]
