# Generated by Django 4.2.5 on 2024-02-29 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0008_carrito_cartitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Envio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_envio', models.CharField(max_length=100, unique=True)),
                ('fecha_envio', models.DateField(blank=True, null=True)),
                ('medio', models.CharField(blank=True, max_length=100, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('enviado', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.cliente')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contabilidad.venta')),
            ],
        ),
    ]
