# Generated by Django 4.2.5 on 2024-03-13 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0010_alter_envio_numero_de_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envio',
            name='numero_de_envio',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
