# Generated by Django 4.2.5 on 2024-03-18 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contabilidad', '0011_alter_envio_numero_de_envio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venta',
            name='condicion',
            field=models.CharField(choices=[('Contado', 'Contado'), ('Cuenta corriente', 'Cuenta corriente'), ('Tarjeta de credito', 'Tarjeta de credito'), ('Debito automatico', 'Debito automatico'), ('Donacion', 'Donacion'), ('online', 'online'), ('Transferencia', 'Transferencia')], max_length=50),
        ),
    ]
